#!/bin/bash
# send_fuzz_data by David Weinman <david@weinman.com>

# This file is licensed under The DO WHAT THE FUCK YOU WANT TO License, see LICENSE for details.


if [ ! $# -eq 1 ]; then
  echo "Usage: send_fuzz_data <data>
Example:

sh$ send_fuzz_data \"1 ++ 2\""
  exit
fi
if [ $(echo $1 | grep -q ":"; echo $?) ]; then
  echo "there's a : in the input, aborting! the scoring system uses the : to parse :("
  exit
fi

DEFENDING_HOST="10.0.26.130"

echo "$1" | nc $DEFENDING_HOST 1337

